//@version=6
library("FibonacciUtils", overlay=true)

// Draws basic Fibonacci extension levels between two prices
export drawExtensions(float startPrice, float endPrice, bool extendRight, color colUp, color colDown, int width) =>
    float diff     = endPrice - startPrice
    array<float> L = array.from(0.0, 0.236, 0.382, 0.5, 0.618, 1.0, 1.618)
    for lvl in L
        float price = endPrice + diff * lvl
        color c     = diff >= 0 ? colUp : colDown
        line.new( bar_index[1], price,bar_index,    price, xloc   = xloc.bar_index,extend = extendRight ? extend.right : extend.none, color  = c, width  = width)